POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "user_email": "adalovelace@example.com",
    "user_password": "adminpass"
}

###

GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxODQwLCJ1c2VyX2VtYWlsIjoiYWRhbG92ZWxhY2VAZXhhbXBsZS5jb20iLCJ1c2VyX3R5cGUiOiJhZG0iLCJpYXQiOjE3NDQ4MzgzMTksImV4cCI6MTc0NDkyNDcxOX0.Wpb6uwkIpT0qmIVScBqhMDGUbDV9P5lr4Pejvs63sb4

###

POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
    "user_email": "johnnash@example.com",
    "user_password": "potpass"
}

###
GET http://localhost:3000/api/users/1936
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxOTM2LCJ1c2VyX2VtYWlsIjoid2FsdGVyZnJlZW1hbkBleGFtcGxlLmNvbSIsInVzZXJfdHlwZSI6ImRvYyIsImlhdCI6MTc0NDgzODQ2NSwiZXhwIjoxNzQ0OTI0ODY1fQ.WqZV7tUdtM8P1UALoSAvCiM29wVBMw8wrDId7Iqsry0

###
GET http://localhost:3000/api/users/adm/1840
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxODQwLCJ1c2VyX2VtYWlsIjoiYWRhbG92ZWxhY2VAZXhhbXBsZS5jb20iLCJ1c2VyX3R5cGUiOiJhZG0iLCJpYXQiOjE3NDQ5NzI0OTksImV4cCI6MTc0NTA1ODg5OX0.jbLfS80nJdivDmUhbVG-hCu5XYENAzxkzmJBu-1CdFA

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "Jack",
    "surname": "Jackson",
    "birthday": "1992-02-09",
    "ht": "090292777D",
    "phone": "0466339965",
    "email": "jackson@example.com",
    "pass": "adminpass",
    "user_type": "adm",
    "creator_id": 1
}

###
POST http://localhost:3000/api/users/6
Content-Type: application/json

{
    "age": 71,
    "mi_date": "2000-12-19",
    "pills": "aspirin"
}


###
DELETE http://localhost:3000/api/users/30


###
GET http://localhost:3000/api/users/info/11

###
GET http://localhost:3000/api/users/recom/6

###

POST http://localhost:3000/api/ai/6
Content-Type: application/json

{
    "status": "warning",
    "patient_instruction": "rintakipu, pääkipu",
    "doctor_note": "Patient ilmoittanut oireeista, tarvi lääkärin tarkistusta."
}


###
POST http://localhost:3000/api/users/recom/6
Content-Type: application/json

{
    "textData": "Testi recommendation"
}

###
POST http://localhost:3000/api/metrics/6
Content-Type: application/json

{
    "sdnn": 131,
    "rmssd": 131,
    "pnn50": 31,
    "lfhf": 1.31,
    "rr_mean": 931,
    "hr": 91,
    "hrv": "Normaali"
}
